name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: GitHub Pages Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Init Checkout
        uses: actions/checkout@v3

      - name: Init PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          check-latest: true
          

      - name: PNPM install and Build
        run: |
          pnpm i
          pnpm build
        env:
          VITE_VAR_NAME: ${{ secrets.VITE_VAR_NAME }}

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist